import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <p className={styles.description}>
          Get started by visting following links
        </p>

        <div className={styles.grid}>
          <a href="/prefetched-nocache" className={styles.card}>
            <h2>The query is prefetched in getServerSideProps</h2>
            <p>Then queryClient is dehydrated and sent down</p>
          </a>

          <a href="/client-only" className={styles.card}>
            <h2>Client Only</h2>
            <p>The query happens only on the client side</p>
          </a>

          <a href="/prefetched" className={styles.card}>
            <h2>Query is prefetched and cached</h2>
            <p>You should see load time decrease after the initial load</p>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
